# Generated by Django 6.0.7 on 2026-07-21 19:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_id', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(choices=[('BOOK', 'Book'), ('ARTICLE', 'Article')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('text_content', models.TextField(blank=True, default='', null=True)),
                ('img_path', models.URLField(blank=True, default='https://via.placeholder.com/600x400', max_length=500, null=True)),
                ('language', models.CharField(default='ar', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('bookdetail_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField(max_length=500)),
                ('pages_count', models.PositiveIntegerField(default=1)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_detail', to='plateform_backend.content')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('articledetail_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('pages_count', models.PositiveIntegerField(default=1)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_detail', to='plateform_backend.content')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('payout_method', models.CharField(blank=True, max_length=100, null=True)),
                ('payout_details', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(default='PENDING', max_length=50)),
                ('payment_method', models.CharField(max_length=100)),
                ('transaction_reference', models.CharField(max_length=255, unique=True)),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='plateform_backend.content')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='plateform_backend.profile')),
            ],
        ),
    ]
