# Generated by Django 6.0.7 on 2026-08-10 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateform_backend', '0002_profile_created_at_alter_profile_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='plateform_backend.profile'),
        ),
    ]
