"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SECURITY
# ============================================================

# في الإنتاج يجب وضع DJANGO_SECRET_KEY في Environment Variables
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "dev-only-secret-key"
)

# محليًا DEBUG=True
# في الإنتاج نضع DEBUG=False
DEBUG = os.getenv("DEBUG", "True").lower() == "true"


# ============================================================
# ALLOWED HOSTS
# ============================================================

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "ALLOWED_HOSTS",
        "127.0.0.1,localhost"
    ).split(",")
    if host.strip()
]


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [

    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party packages
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",

    # Our application
    "plateform_backend",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [

    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URL / WSGI
# ============================================================

ROOT_URLCONF = "core.urls"

WSGI_APPLICATION = "core.wsgi.application"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# DATABASE
# ============================================================
#
# DEVELOPMENT
# --------------------
# Django
#   ↓
# Docker django_web
#   ↓
# Docker django_db
#   ↓
# PostgreSQL
#
#
# PRODUCTION
# --------------------
# Django
#   ↓
# DATABASE_URL
#   ↓
# Supabase PostgreSQL
#
# ============================================================


if os.getenv("DATABASE_URL"):

    # --------------------------------------------------------
    # PRODUCTION
    # --------------------------------------------------------
    #
    # إذا كان DATABASE_URL موجودًا، سيتم استخدامه.
    # هذا هو الإعداد الذي سنستخدمه عند نشر المشروع.
    #

 DATABASES = {
    'default': dj_database_url.config(
        default=(
            f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}"
            f"@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}"
            f"/{os.getenv('DB_NAME')}"
        ),
        conn_max_age=0,
    )
}
else:

    # --------------------------------------------------------
    # DEVELOPMENT / DOCKER
    # --------------------------------------------------------
    #
    # أثناء التطوير يستخدم Django PostgreSQL الموجودة
    # داخل Docker Compose.
    #
    # اسم السيرفر هنا هو:
    #
    #     db
    #
    # وليس:
    #
    #     127.0.0.1
    #
    # لأن db هو اسم خدمة PostgreSQL في docker-compose.yml.
    #

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",

            "NAME": os.getenv(
                "DB_NAME",
                "my_django_db"
            ),

            "USER": os.getenv(
                "DB_USER",
                "my_db_user"
            ),

            "PASSWORD": os.getenv(
                "DB_PASSWORD",
                "my_secure_password"
            ),

            "HOST": os.getenv(
                "DB_HOST",
                "db"
            ),

            "PORT": os.getenv(
                "DB_PORT",
                "5432"
            ),
        }
    }


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
        "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.MinimumLengthValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.CommonPasswordValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "static/"


# ============================================================
# CORS
# ============================================================

# أثناء التطوير المحلي
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]


# ============================================================
# CSRF
# ============================================================

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]


# ============================================================
# DJANGO REST FRAMEWORK
# ============================================================

REST_FRAMEWORK = {

    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],

}


# ============================================================
# CORS SETTINGS
# ============================================================

# مؤقتًا أثناء التطوير.
#
# لاحقًا عند نشر المشروع سنجعلها أكثر أمانًا
# ونسمح فقط بعنوان Frontend الخاص بنا.
#

CORS_ALLOW_ALL_ORIGINS = True


# ============================================================
# CORS HEADERS
# ============================================================

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]


# ============================================================
# CORS METHODS
# ============================================================

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]